### ISSUE TITLE
Django 4.1 error

### ISSUE THREAD

**Issue by nengkya** [andarms/scribimus#1]
[Help]

raise ImproperlyConfigured(msg.format(name=self.urlconf_name)) from e

django.core.exceptions.ImproperlyConfigured: The included URLconf 'scribimus.urls' does not appear to have any patterns in it. If you see the 'urlpatterns' variable with valid patterns in the file then the issue is probably caused by a circular import.
---------------------------------------------------------------------------------------

Code :

urlpatterns=[
path(r'^members', include('apps.member.urls', namespace='members'))
]

**Comment by andarms** [comment]
Hello @nengkya this it's one of the many dead projects that I own. I was created with django 1.8 that's why it's not working. Also I didn't add too much functionality it's just some models.

**Comment by nengkya** [comment]
Do you have more django like wattpad ?

**Comment by andarms** [comment]
not, this never works and I did not do anything similar to this

**Comment by andarms** [comment]
do you need a watppad clone?

**Comment by nengkya** [comment]
Yes siR,
